# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reason', models.CharField(choices=[('order_created', 'Sipariş oluşturuldu'), ('order_cancelled', 'Sipariş iptal edildi'), ('admin_adjustment', 'Admin stok düzenlemesi'), ('initial_stock', 'İlk stok girişi')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
